# === TYPE (분류용) ===
- name: 'type: page'
  color: '1abc9c'
  description: 페이지 전체 구현 작업

- name: 'type: subpage'
  color: '16a085'
  description: 페이지 내 하위 단위 화면 구현

- name: 'type: component'
  color: '27ae60'
  description: 특정 컴포넌트 구현 또는 수정

# === TYPE ===
- name: ':sparkles: feature'
  color: '7cd36d'
  description: 새로운 기능 및 코드 추가

- name: ':ocean: update'
  color: '53b4d1'
  description: 기존 기능 또는 코드 수정

- name: ':fire: remove'
  color: 'ff6666'
  description: 기능, 코드 또는 파일 삭제

- name: ':bug: bug'
  color: 'd73a4a'
  description: 버그 수정

- name: ':ambulance: hotfix'
  color: 'b60205'
  description: 긴급/치명적 버그 수정

- name: ':recycle: refactor'
  color: '8e44ad'
  description: 코드 리팩토링

- name: ':art: style'
  color: 'fca0ff'
  description: UI 스타일 및 레이아웃 변경

- name: ':memo: docs'
  color: 'cfd3d7'
  description: 문서 수정 또는 작성

- name: ':pencil2: typo'
  color: 'e1e4e8'
  description: 오타 및 간단한 문구 수정

- name: ':bulb: comment'
  color: 'f0db4f'
  description: 코드 주석 추가 또는 변경

- name: ':alien: api'
  color: '9b59b6'
  description: 외부 API 관련 변경

- name: ':building_construction: structure'
  color: '34495e'
  description: 프로젝트 디렉토리 구조 변경

- name: ':package: move'
  color: 'f39c12'
  description: 파일 이동 또는 경로 수정

- name: ':wheelchair: a11y'
  color: '3498db'
  description: 접근성 향상 관련 작업

- name: ':iphone: responsive'
  color: '1abc9c'
  description: 반응형 디자인 작업

- name: ':egg: easter-egg'
  color: 'ffb347'
  description: 이스터 에그 추가 또는 업데이트

- name: ':tada: init'
  color: '5319e7'
  description: 초기 커밋

- name: ':rocket: deploy'
  color: '2ecc71'
  description: 배포 관련 작업

# === DEPENDENCY ===
- name: ':heavy_plus_sign: dependency:add'
  color: '0366d6'
  description: 외부 패키지 추가

- name: ':heavy_minus_sign: dependency:remove'
  color: 'd93f0b'
  description: 외부 패키지 제거

# === STATUS ===
- name: 'status: ready'
  color: '0e8a16'
  description: 머지 준비 완료

- name: 'status: in progress'
  color: 'fbca04'
  description: 현재 작업 중

- name: 'status: blocked'
  color: 'b60205'
  description: 다른 작업 또는 이슈에 의해 막힘

# === PRIORITY ===
- name: 'priority: high'
  color: 'd93f0b'
  description: 긴급하거나 중요한 작업

- name: 'priority: medium'
  color: 'fbca04'
  description: 보통 우선순위 작업

- name: 'priority: low'
  color: 'cfd3d7'
  description: 낮은 우선순위 작업