name: Create GitHub Labels

on:
  workflow_dispatch:
  push:
    paths:
      - '.github/labels.yml'

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Sync labels from YAML
        uses: EndBug/label-sync@v2
        with:
          config-file: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
